### ISSUE TITLE
uuid 是和账号对应的吗？

### ISSUE THREAD

**Issue by mingyue0094** [h88782481/Chat-Share#2]
http://DOMAIN_CHATGPT/?token=uuid

---
uuid 是和后台的chat_share账号绑定的，还是与模型平台账号绑定的？

比如在 chat_share 设置完成后，是否可以仅 发 http://DOMAIN_CHATGPT/?token=uuid 给朋友直接使用 ？

**Comment by h88782481** [comment]
没看懂啥意思
