### ISSUE TITLE
项目走向建议

### ISSUE THREAD

**Issue by wx-11** [h88782481/Chat-Share#4]
lq的是2api 既然基于他应该开放逆向池功能,这个作为前置代理,实现类似于one/new api的用户管理功能,而不是只使用 镜像功能.因为镜像太多而且有完善隔离逻辑.用这个前景不大 而且重复造轮子 竞争力小
初步建议是:(也是为了更加完善)
- 接管管控chat2api的后台 实现批量添加账号
- 支持分用户 传入用户自定义key调用api 前台显示统计信息
- 账号多方面分类 显示plus/普号/冷却/gpts等使用情况/可用数量

用户可以基于本系统实现简易的api自由(比如简单的账号失败自动刷新/禁用以及重试) 也可以接入api中转 我感觉只逆向的话其实这些功能够用

后期可以支持更多高级功能
- 通过秦始皇项目实现claude2api(因为闭源 所以等有代替品再实现可能会更好)
- 使 claude 像gpt功能全面

当然 以上个人拙见 可能作者是为了玩镜像 那不考虑发展 当做自己玩玩就不需要考虑这些建议  只是基于自建共享镜像已经有更好的成熟方案 要脱颖而出压力会比较大 加油

**Comment by h88782481** [comment]
这个就是拿来共享用的，不需要别的复杂的东西，做这个的初衷就是个人用户共享自己的账号
